export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ params, children }) {
    return (
        <html lang={params.locale}>
            <body>{children}</body>
        </html>
    );
}
